apiVersion: v1
kind: ConfigMap
metadata:
  name: faturamento-edi-config
data:
  PORT: "80"
  TZ: "America/Sao_Paulo"
  CAMINHO_EDI: "/mnt/sankhya/repositorio/Integracao/Faturamento/EDI"
  CAMINHO_PDF: "/mnt/sankhya/repositorio/Integracao/Faturamento/Romaneio"

---

apiVersion: v1
kind: Secret
metadata:
  name: faturamento-edi-secret
type: Opaque
data:
  # Por favor, substitua os valores abaixo por suas credenciais reais em Base64.
  # Exemplo: echo -n "seu_valor" | base64


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: faturamento-edi-deployment
  labels:
    app: faturamento-edi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faturamento-edi
  template:
    metadata:
      labels:
        app: faturamento-edi
    spec:
      containers:
      - name: faturamento-edi
        image: seu-usuario-docker/faturamento-edi:latest # Substitua pela sua imagem Docker
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: faturamento-edi-config
        - secretRef:
            name: faturamento-edi-secret
        # Se você for usar PersistentVolume para o compartilhamento SMB,
        # adicione a configuração de volume aqui e remova o mount-smb.sh do CMD.
        # volumeMounts:
        #   - name: smb-volume
        #     mountPath: /mnt/sankhya
      # volumes:
      #   - name: smb-volume
      #     persistentVolumeClaim:
      #       claimName: smb-pvc # Substitua pelo nome do seu PersistentVolumeClaim

---

apiVersion: v1
kind: Service
metadata:
  name: faturamento-edi-service
  labels:
    app: faturamento-edi
spec:
  selector:
    app: faturamento-edi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Ou NodePort, dependendo da sua necessidade e ambiente Kubernetes
